### PR TITLE
Get latest develop from NREL repo

### PR DESCRIPTION
**Pull request by JasonGlazer**
Pull request overview
---------------------
Please change this line to a description of the pull request, with useful supporting information including whether it is a new feature, or fixes a defect, a cross reference to any defects addressed in this PR, the type of changes to be made, and whether diffs are expected/justified based on this change.

### Work Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Title of PR should be user-synopsis style (clearly understandable in a standalone changelog context)
 - [ ] At least one of the following appropriate labels must be added to this PR to be consumed into the changelog:
   - Defect: This pull request repairs a github defect issue.  The github issue should be referenced in the PR description
   - Refactoring: This pull request includes code changes that don't change the functionality of the program, just perform refactoring
   - NewFeature: This pull request includes code to add a new feature to EnergyPlus
   - Performance: This pull request includes code changes that are directed at improving the runtime performance of EnergyPlus
   - DoNoPublish: This pull request includes changes that shouldn't be included in the changelog

### Review Checklist
This will not be exhaustively relevant to every PR.
 - [ ] Code style (parentheses padding, variable names)
 - [ ] Functional code review (it has to work!)
 - [ ] If defect, results of running current develop vs this branch should exhibit the fix
 - [ ] CI status: all green or justified
 - [ ] Performance: CI Linux results include performance check -- verify this
 - [ ] Unit Test(s)
 - C++ checks:
   - [ ] Argument types
   - [ ] If any virtual classes, ensure virtual destructor included, other things
 - IDD changes:
   - [ ] Verify naming conventions and styles, memos and notes and defaults
   - [ ] Open windows IDF Editor with modified IDD to check for errors
   - [ ] If transition, add rules to spreadsheet
   - [ ] If transition, add transition source
   - [ ] If transition, update idfs
 - [ ] If new idf included, locally check the err file and other outputs
 - [ ] Documentation changes in place
 - [ ] Changed docs build successfully
 - [ ] ExpandObjects changes?
 - [ ] If output changes, including tabular output structure, add to output rules file for interfaces

### CODE REVIEW

**Comment by JasonGlazer** [comment]
@jmarrec I created this pull request just to update your "develop" with the NREL repo "develop". I think that is necessary to include your code with the current NREL develop code to make sure the testing goes ok. When you get a chance please merge this. If you know of a different way to do this, please let me know.

**Comment by jmarrec** [comment]
I'm not sure I follow. Do you want me to rebase a given branch to the latest develop?  If so which?

My jmarrec/develop shouldn't have anything useful on it (if I did a PR from my "develop" branch, that's a mistake, I should have branched before), I just use it to track this upstream repo.

I think you, being part of the repo, should be able to push directly to my branches for which I have created a PR (if not, I just need to authorize that, let me know), so that includes merging the NREL/develop into it if need be.

**Comment by JasonGlazer** [comment]
It is likely just my lack of understanding. I don't think I have worked across a forked repo before. The NREL develop branch has had a (kind of) significant change. The CI on 6169 pull request for the water rates failed because of the year of the license. I would like to run tests locally on my machine and on the CI with the fixes to the year of the license. Those fixes are in the NREL develop branch but not your repo. So if you could either approve this pull request or suggest a different approach, I would appreciate it.

**Comment by JasonGlazer** [comment]
@jmarrec I don't seem to be authorized to merge this pull request. Can you give me permission or else merge it?

**Comment by jmarrec** [comment]
We have no business being on my develop. IIUC you want to pull NREL/develop in jmarrec/HandleWaterUtilityCostTariffs? I'll do that.

**Comment by JasonGlazer** [comment]
Thanks.

**Pull request merged**
